name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - run: mvn clean package
      - run: |
          gh release create ${{ github.ref_name }} target/*.jar \
            --title "${{ github.ref_name }}" \
            --notes "github-actions release for tag ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
